### ISSUE TITLE
tcp error on windows

### ISSUE THREAD

**Issue by marcelvanherk** [albhasan/luaRserve#1]
Hi,

just included in in my windows project; to make it work I had to modify the calltcp function, adding socket creation:

function calltcp(rsserver, rsport, msg)
  tcp = socket.tcp()  -- mvh 20160902
  tcp:settimeout(1, 'b')
  tcp:connect(rsserver, rsport)
  if msg and msg ~= " " then
    tcp:send(msg)
  end
  local s, status, partial = tcp:receive('*a')
  tcp:close()
  return s, status, partial
end

Now test runs fine.

One question: how do you load a table from lua into R with luarserve?

regards, Marcel

**Comment by albhasan** [comment]
Hello there,
I just committed your change. However, I didn't test it on Windows, just in Linux and it works. Thanks.

Regarding your question, I just send the Lua data to Rserve as a string. It's inefficient but I didn't have time for more. I guess you can reverse the parsing process and encode your data using the [dev documentation](http://rforge.net/Rserve/dev.html). However, I think in the long term it would be worth to write a mapping from R to Lua's data types. I mean, write Lua objects for R's vector, matrix, data frame, etc. My point is, R objects can be composed in several way, so, this is difficult to generalize.

Cheers!
