### ISSUE TITLE
Pretty much full recode

### ISSUE THREAD

**Issue by marcelvanherk** [albhasan/luaRserve#3]
Hi,

I pretty much recoded the whole thing. Please have a look.

-- Rserve client - original from https://github.com/albhasan/luaRserve
  R client software with Lua representation of some R objects. 
  Sample usage:

  R = require "rclient"
  R.connect()
  R("library(survival)")  -- same as R.evaluateVoid("library(survival)")
  a = R.evaluate('d <- c(1,2,3,NA); e <- c("red", "white", NA, "blue"); f <- c(NA,TRUE,TRUE,FALSE); mydata <- data.frame(d,e,f)')
  printtable(a)

  f = frame:new({{1,5,3},{'a','b','c'},{0,1,2}}, {'time','letters','status'})
  --f:readCSV(filename)
  R.f = f
  R('f$SurvObj <- with(f, Surv(time, status == 2))')
  printtable(R.f)

  m = matrix:new({{1,1},{1,-1},{-1,1},{-1,-1}})
  R.m = m
  R('m = solve(m)')
  printtable(R.m)

  f = factor:new('red', 'green', 'blue', 'red')
  printtable(f)
  R.f = f
  printtable(R.f)

  v = {1,2,3,4}
  R.v = v
  printtable(R.v)

[Rclient.zip](https://github.com/albhasan/luaRserve/files/465396/Rclient.zip)

Marcel

**Comment by albhasan** [comment]
Hi, great! - Thanks!
